version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    env_file:
      - ./config/dev.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: yarn start:dev
    networks:
      - api-postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    env_file:
      - ./config/dev.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-postgres

networks:
  api-postgres: null
volumes:
  pgdata: null
