version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    env_file:
      - ./config/dev.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: yarn start:dev
    networks:
      - api-cassandra
      - api-postgres
    depends_on:
      - cassandra
      - postgres

  cassandra:
    image: cassandra:4.0
    environment:
      CASSANDRA_CONTACT_POINT: ${CASSANDRA_CONTACT_POINT}
      CASSANDRA_LOCAL_DATA_CENTER: ${CASSANDRA_LOCAL_DATA_CENTER}
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra
    networks:
      - api-cassandra

  postgres:
    image: postgres:14.1-alpine
    env_file:
      - ./config/dev.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-postgres

networks:
  api-cassandra: null
  api-postgres: null
volumes:
  cassandra: null
  pgdata: null
